### ISSUE TITLE
Error: not implemented

### ISSUE THREAD

**Issue by genckaptan55** [nfriedly/node-unblocker#107]
I am unable to make nodeunblocker work. I got this error when i click on 'Go' button

![problem](https://user-images.githubusercontent.com/13719393/45782341-416d3a00-bc6b-11e8-8ad6-32f3793e3479.png)

**Comment by nfriedly** [comment]
Oh, it might be related to gatlin. Can you try out the 'simple' example and let me know if it works?

Also, what version of node.js are you on? (`node -v`)

My internet is down except for on my phone, but I'll take a closer look once I get a chance.

**Comment by nfriedly** [comment]
Hey, I got on a computer and tested it out, it seemed to work for me. Can you give me more details about your setup:

* What version of node.js are you on (`node -v`)?
* What website were you trying to proxy?
* Can it proxy *any* website, e.g. asdf.com?
* Can you give me the full stack trace as text? (Click the icon in the upper-right of the window, and it should have a menu that includes Edit -> Select All and then do it again for Edit -> Copy)

**Comment by genckaptan55** [comment]
- My node version is v0.10.48
- It doesnt matter what website it is 
- It cant proxy not even one website
- Output:

login as: root
root@46.105.148.237's password:
Last login: Thu Sep 20 00:14:53 2018 from 78.182.103.188
[root@s1 ~]# sxreen -ls
-bash: sxreen: command not found
[root@s1 ~]# screen -ls
There is a screen on:
        4335.unblock    (Detached)
1 Socket in /var/run/screen/S-root.
    at ServerResponse.OutgoingMessage.setHeader (http.js:724:11)
    at Domain.<anonymous> (/home/agarnew/public_html/node_modules/gatling/gatling.js:81:22)
    at Domain.emit (events.js:95:17)
    at process._fatalException (node.js:269:31)
error Error: not implemented
    at Transform._transform (_stream_transform.js:154:9)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Transform.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at _stream_readable.js:579:7
    at process._tickDomainCallback (node.js:502:13)
Error sending 500! Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:724:11)
    at Domain.<anonymous> (/home/agarnew/public_html/node_modules/gatling/gatling.js:81:22)
    at Domain.emit (events.js:95:17)
    at process._fatalException (node.js:269:31)
Gatling worker thread 3 up and listening

**Comment by genckaptan55** [comment]
Okey I solved the problem with nodejs version. The problem was my nodejs version and now its ok. The thing is i want a website address.. Lets say i want to use 'www.nodeunblocker.org' but if i not put the port number like 'www.nodeunblocker.org:8080' then script doesnt work. What i need to do for it?

**Comment by nfriedly** [comment]
Try running ` npm start -- --port 80`

**Comment by genckaptan55** [comment]
That's the full output when i tried to use `npm start -- --port 80`

[root@s1 public_html]# screen -S unblock
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at listenOnMasterHandle (net.js:1354:21)
    at rr (internal/cluster/child.js:122:12)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:80
    at listenOnMasterHandle (net.js:1353:16)
    at rr (internal/cluster/child.js:122:12)
    at Worker.send (internal/cluster/child.js:89:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at listenOnMasterHandle (net.js:1354:21)
    at rr (internal/cluster/child.js:122:12)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:80
    at listenOnMasterHandle (net.js:1353:16)
    at rr (internal/cluster/child.js:122:12)
    at Worker.send (internal/cluster/child.js:89:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at listenOnMasterHandle (net.js:1354:21)
    at rr (internal/cluster/child.js:122:12)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by nfriedly** [comment]
I think `EADDRINUSE` means something else is using port 80. What's at http://localhost:80/ for you?

**Comment by genckaptan55** [comment]
My server is a Centos 6 and I installed Cpanel.

**Comment by nfriedly** [comment]
It looks like it works for me now at http://agarnew.com/

**Comment by genckaptan55** [comment]
When you want to proxy a website by clicking to"Go" button then it returns 404

**Comment by genckaptan55** [comment]
Can I use host variable? For example i go to address agarnew.com and wrote a website to proxy and then hit Go button. If i write host variable as `host: 'agarnew.com:8080'`, will the app work and take me to address agarnew.com:8080/proxy/thewebsitetoproxy?

**Comment by nfriedly** [comment]
Actually yeah, you probably can do something like that, keep your existing web server on port 80, but  in the `public/index.html` file change `window.location.pathname = 'proxy/' + url;` to `window.location = 'http://agarnew.com:8080/proxy/' + url;`

I don't think you'll need any change to the Unblocker config.

**Comment by nfriedly** [comment]
It looks like that is working for you now, so I'm going to go ahead and close this for now. Feel free to re-open if necessary.
