### ISSUE TITLE
Using NodeUnblocker.com results in errors of basic websites 

### ISSUE THREAD

**Issue by SoulSen** [nfriedly/node-unblocker#126]
Some websites like google.com or youtube.com can't be accessed because of this resulting error 

https://ghostbin.co/paste/przn8

I'm not sure what exactly is causing it, so it would be nice to figure it out.

**Comment by nfriedly** [comment]
Oh, yikes! That shouldn't happen. 

I'm going to copy the error message here just to make the ticket more serchable:

```
2019-12-18T23:54:11.062306+00:00 app[web.1]: TypeError: option sameSite is invalid

2019-12-18T23:54:11.062311+00:00 app[web.1]:     at Object.serialize (/app/node_modules/unblocker/node_modules/cookie/index.js:174:15)

2019-12-18T23:54:11.062317+00:00 app[web.1]:     at /app/node_modules/unblocker/lib/cookies.js:68:34

2019-12-18T23:54:11.062319+00:00 app[web.1]:     at Array.map (<anonymous>)

2019-12-18T23:54:11.062322+00:00 app[web.1]:     at rewriteCookiesAndLinks (/app/node_modules/unblocker/lib/cookies.js:62:50)

2019-12-18T23:54:11.062324+00:00 app[web.1]:     at /app/node_modules/unblocker/lib/proxy.js:76:13

2019-12-18T23:54:11.062326+00:00 app[web.1]:     at arraySome (/app/node_modules/lodash/lodash.js:726:11)

2019-12-18T23:54:11.062331+00:00 app[web.1]:     at Function.some (/app/node_modules/lodash/lodash.js:9897:14)

2019-12-18T23:54:11.062333+00:00 app[web.1]:     at proxyResponse (/app/node_modules/unblocker/lib/proxy.js:75:43)

2019-12-18T23:54:11.062334+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/unblocker/lib/proxy.js:50:17)

2019-12-18T23:54:11.062336+00:00 app[web.1]:     at Object.onceWrapper (events.js:412:26)

2019-12-18T23:54:11.062597+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/proxy/https://www.youtube.com/" host=nodeunblocker-soul.herokuapp.com request_id=227a39d4-7bbb-4f63-94b9-f18b9c69a5a2 fwd="73.116.90.44" dyno=web.1 connect=1ms service=220ms status=503 bytes=0 protocol=http
```

**Comment by nfriedly** [comment]
Ok, updating the `cookie` library to the latest fixes that specific issue, so I did that for now. I believe that if you re-deploy your app, it will get the latest version and not have this issue any more.

It does make me a little concerned that there may be similar errors lurking, but we'll deal with those if/when they arise.

**Comment by SoulSen** [comment]
Alright thanks! I will be sure to open another issue in case this does happen.
