### ISSUE TITLE
sometime error and stuck when use in docker

### ISSUE THREAD

**Issue by bobwatcherx** [nfriedly/node-unblocker#255]
i made node unblocker as docker . the start was smooth. but approximately 24 hours. an error occurred. and I had to restart my docker and it went back to normal. but it happens almost once a day. when I use for scraping https://javhd.today

```
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: connect ETIMEDOUT 104.21.64.253:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Error: getaddrinfo ENOTFOUND uncensored
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
ReferenceError: unblockerConfig is not defined
    at /code/app.js:77:59
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at next (/code/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/code/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at /code/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/code/node_modules/express/lib/router/index.js:346:12)
    at next (/code/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/code/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:400:28)
Error: getaddrinfo ENOTFOUND uncensored
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: getaddrinfo ENOTFOUND english
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by nfriedly** [comment]
Nice.

What's in your app.js on and around line 77?

The other errors look like ones that shouldn't crash the server, but that "ReferenceError: unblockerConfig is not defined" might take it down. (Mostly it looks like it's attempting to look up the domain "english" but, of course, that's not a valid domain. I see `>>> EngLish ` in the source, which isn't valid HTML, so maybe that's confusing the parser?)

**Comment by nfriedly** [comment]
Oh, wait, that's [this](https://github.com/nfriedly/nodeunblocker.com/blob/188ebf29b9572ad0f1aafe3c5d9ee7ac7c71c3f0/app.js#L77), isn't it

```js
res.redirect(unblockerConfig.prefix + site);
```

**Comment by nfriedly** [comment]
Ok, update to the latest version of nodeunblocker.com and see if that fixes it. 

Apparently something in that site was triggering the `/no-js` url, and that had a latent bug because I hadn't tested it with javascript disabled in the browser after reworking the config.
