### ISSUE TITLE
After npm start node-unblocker throw errors.

### ISSUE THREAD

**Issue by singerxt** [nfriedly/node-unblocker#39]
Hello ! 

I fallowed steps from "installation on your system" and after ```npm start```
I'm seeing fallowing error:
```
MBP-Mateusz:node-unblocker mateusz$ npm start

> node-unblocker@0.13.1 start /Users/mateusz/Desktop/node-unblocker
> ./node_modules/gatling/gatling.js --threads 2 ./app.js

module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mateusz/Desktop/node-unblocker/node_modules/iconv/lib/iconv.js:27:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! node-unblocker@0.13.1 start: `./node_modules/gatling/gatling.js --threads 2 ./app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-unblocker@0.13.1 start script './node_modules/gatling/gatling.js --threads 2 ./app.js'.
npm ERR! This is most likely a problem with the node-unblocker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/gatling/gatling.js --threads 2 ./app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-unblocker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mateusz/Desktop/node-unblocker/npm-debug.log
```
any thoughts ?

**Comment by nfriedly** [comment]
Hey, sorry for the delay, I'm taking a look now

**Comment by singerxt** [comment]
@nfriedly Thanks!! Your app is awesome ;-)

**Comment by nfriedly** [comment]
Hum.. it's working on my laptop (OS X). Did `npm rebuild` report any errors?

If not, then you can actually visit most websites without the iconv stuff - anything that's UTF-8 and even most text in other charsets will work without modification. To disable iconv, you currently have to do some edits to remove the `encoding` stuff` in https://github.com/nfriedly/node-unblocker/blob/master/lib/proxy.js: comment out line 9, 134, and 144, then combine lines 140 and 141 into something like this:

    remote_response = remote_response.pipe(urlPrefixStream)

Let me know if that works for you.

**Comment by singerxt** [comment]
@nfriedly Thanks for respond I'll checkout soon. Thanks for your help!

**Comment by singerxt** [comment]
Hello!

@nfriedly thanks that helped me a lot :-) !

Unfortunately now when I run app in my localhost after fill the form I see 

```
Gatling worker thread 1 up and listening
error RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at rewriteUrls (/Users/mateusz/Desktop/node-unblocker/lib/urlprefixstream.js:45:19)
    at Stream.write (/Users/mateusz/Desktop/node-unblocker/lib/urlprefixstream.js:86:17)
    at Stream.stream.write (/Users/mateusz/Desktop/node-unblocker/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:129:20)
    at drain (/Users/mateusz/Desktop/node-unblocker/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/mateusz/Desktop/node-unblocker/node_modules/through/index.js:45:5)
    at Stream.write (/Users/mateusz/Desktop/node-unblocker/lib/urlprefixstream.js:89:14)
    at Stream.stream.write (/Users/mateusz/Desktop/node-unblocker/node_modules/through/index.js:26:11)
Error sending 500! Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.res.setHeader (/Users/mateusz/Desktop/node-unblocker/node_modules/connect/lib/patch.js:59:22)
    at Domain.<anonymous> (/Users/mateusz/Desktop/node-unblocker/node_modules/gatling/gatling.js:81:22)
    at Domain.emit (events.js:107:17)
    at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
    at process._fatalException (node.js:233:33)
Gatling worker thread 3 up and listening

(null):0
(null)

RangeError: Maximum call stack size exceeded
Gatling worker thread 4 up and listening
```

any thoughts ? ;-)

**Comment by nfriedly** [comment]
What version of node.js are you on? (Run `node -v`)

**Comment by singerxt** [comment]
Hello @nfriedly I'm using node v0.12.0 Hopefully this will be helpful ;-)

**Comment by nfriedly** [comment]
Oh, yea, it is. I haven't worked on this in a while, so it hasn't been tested on the 0.12 releases. You could try updating to the latest (0.12.2), but if that doesn't fix it, then you might have to downgrade to 0.10.x - You can download old versions from http://nodejs.org/dist/ I thin http://nodejs.org/dist/v0.10.38/node-v0.10.38-darwin-x64.tar.gz is the one you'd need if 0.12.2 doesn't work.

Sorry about that. I'll work 0.12 support whenever I have the time, but it might be a little while. (This was originally written for node v0.4, so there's probably some cruft that just isn't supported anymore.)

**Comment by singerxt** [comment]
Oh thanks!! That's make sense. I'll try to fix that and create PR Thanks!!

**Comment by nfriedly** [comment]
Btw, starting with unblocker v0.14, everything should compatible with node v0.12, and I also just put out a 1.0 release with some big changes. Please try out one of those and file a new bug if you run into any issues there.

**Comment by singerxt** [comment]
Of course I will thanks!!!!
